feat(ci): Run npm audit signatures

diff --git a/setup/action.yaml b/setup/action.yaml
--- a/setup/action.yaml
+++ b/setup/action.yaml
@@ -83,6 +83,22 @@ runs:
       run: |
         echo "//npm.pkg.github.com/:_authToken=${{ inputs.github-npm-registry-personal-access-token }}" >> ~/.npmrc
 
+    - name: Determine package manager
+      id: package-manager
+      working-directory: ${{ inputs.working-directory }}
+      shell: bash
+      run: |
+        if [ -e "yarn.lock" ]
+        then
+          echo "package-manager=yarn" >> "$GITHUB_OUTPUT"
+        elif [ -e "package-lock.json" ]
+        then
+          echo "package-manager=npm" >> "$GITHUB_OUTPUT"
+        else
+          echo "ERROR: Could not determine package manager. Neither package-lock.json nor yarn.lock found." >&2
+          exit 66 # EX_NOINPUT
+        fi
+
     - name: Install dependencies
       if: steps.cache.outputs.cache-hit != 'true'
       working-directory: ${{ inputs.working-directory }}
@@ -96,12 +112,19 @@ runs:
           export GH_REGISTRY_TOKEN="$GITHUB_NPM_REGISTRY_PERSONAL_ACCESS_TOKEN"
         fi
 
-        if [ -e "yarn.lock" ]
+        if [ "${{ steps.package-manager.outputs['package-manager'] }}" = "yarn" ]
         then
           yarn install --immutable
         else
           npm ci
         fi
+
+    - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
+      if: steps.cache.outputs.cache-hit != 'true' && steps.package-manager.outputs['package-manager'] = 'npm'
+      working-directory: ${{ inputs.working-directory }}
+      shell: bash
+      run: |
+        npm audit signatures
 
     - name: Run prepare npm script
       if: >
