chore: Kebab case for inputs

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -12,7 +12,7 @@ name: Create Release
 on:
   workflow_call:
     inputs:
-      release_type:
+      release-type:
         description: 'Type of release (major, minor, patch, or prerelease)'
         type: string
         default: 'patch'
@@ -34,13 +34,13 @@ jobs:
     steps:
       - name: Verify inputs
         run: |
-          if ! echo "${{ inputs.release_type }}" | grep -qE '^(major|minor|patch|prerelease)$'
+          if ! echo "${{ inputs.release-type }}" | grep -qE '^(major|minor|patch|prerelease)$'
           then
-            echo "Invalid release_type: ${{ inputs.release_type }}. Must be one of: major, minor, patch, prerelease."
+            echo "Invalid release-type: ${{ inputs.release-type }}. Must be one of: major, minor, patch, prerelease."
             exit 64 # EX_USAGE
           fi
 
-          if [ "${{ inputs.release_type }}" = "prerelease" ]
+          if [ "${{ inputs.release-type }}" = "prerelease" ]
           then
             echo "ERROR: Prerelease not supported yet." # TODO Support prerelease
             exit 64 # EX_USAGE
@@ -66,7 +66,7 @@ jobs:
           # inputs.* directly to make it easier to copy it to separate
           # file for testing
           PACKAGE_MANAGER: ${{ steps.setup.outputs.package-manager }}
-          RELEASE_TYPE: ${{ inputs.release_type }}
+          RELEASE_TYPE: ${{ inputs.release-type }}
         run: |
           echo "::group::Prepare semantic-release configuration"
           # TODO Move this to separate package, that can be installed, together with dependencies
