Revert "Don’t use deprecated :: commands"
This reverts commit 6ec1e2d195b13002780a048ea8f2a149a1e03371.

diff --git a/.github/workflows/docker-build-push.yaml b/.github/workflows/docker-build-push.yaml
--- a/.github/workflows/docker-build-push.yaml
+++ b/.github/workflows/docker-build-push.yaml
@@ -138,7 +138,7 @@ jobs:
 
           if [ -z "${PREVIOUS_GIT_REF}" ]
           then
-            echo "ERROR: No previous git reference provided, cannot determine old version." >&2
+            echo "::error::No previous git reference provided, cannot determine old version." >&2
             exit 64 # EX_USAGE
           else
             # Try to get the old version from the previous git reference
@@ -147,7 +147,7 @@ jobs:
           OLD_VERSION="$(git show "${PREVIOUS_GIT_REF}":package.json 2>/dev/null | jq -r '.version')"
           if [ -z "$OLD_VERSION" ]
           then
-            echo "ERROR: Failed to retrieve previous version from git ref '${PREVIOUS_GIT_REF}'" >&2
+            echo "::error::Failed to retrieve previous version from git ref '${PREVIOUS_GIT_REF}'" >&2
             exit 65 # EX_DATAERR
           fi
           echo "old_version=$OLD_VERSION" | tee -a "$GITHUB_OUTPUT"
