Validate required inputs

diff --git a/.github/workflows/docker-build-push.yaml b/.github/workflows/docker-build-push.yaml
--- a/.github/workflows/docker-build-push.yaml
+++ b/.github/workflows/docker-build-push.yaml
@@ -67,11 +67,11 @@ on:
         type: string
         default: 'eu-central-1'
       amazon_role_to_assume:
-        description: 'AWS IAM role to assume'
+        description: 'AWS IAM role to assume. Required, if amazon_enable is true'
         type: string
         default: ''
       amazon_ecr_registry:
-        description: 'ECR registry URL'
+        description: 'ECR registry URL. Required, if amazon_enable is true'
         type: string
         default: ''
       amazon_ecr_repository:
@@ -85,7 +85,7 @@ on:
         type: boolean
         default: false
       google_project_id:
-        description: 'Google Cloud project ID'
+        description: 'Google Cloud project ID. Required, if google_enable is true'
         type: string
         default: ''
       google_registry:
@@ -93,7 +93,7 @@ on:
         type: string
         default: 'europe-west3-docker.pkg.dev'
       google_repository:
-        description: 'Google Artifact Registry repository path'
+        description: 'Google Artifact Registry repository path. Required, if google_enable is true'
         type: string
         default: ''
 
@@ -362,6 +362,28 @@ jobs:
       id-token: write
 
     steps:
+      - name: Validate required inputs
+        env:
+          AMAZON_AWS_REGION: ${{ inputs.amazon_aws_region }}
+          AMAZON_ROLE_TO_ASSUME: ${{ inputs.amazon_role_to_assume }}
+          AMAZON_ECR_REGISTRY: ${{ inputs.amazon_ecr_registry }}
+        run: |
+          if [ -z "$AMAZON_AWS_REGION" ]
+          then
+            echo "::error::amazon_aws_region is required when amazon_enable is true"
+            exit 64 # EX_USAGE
+          fi
+          if [ -z "$AMAZON_ROLE_TO_ASSUME" ]
+          then
+            echo "::error::amazon_role_to_assume is required when amazon_enable is true"
+            exit 64 # EX_USAGE
+          fi
+          if [ -z "$AMAZON_ECR_REGISTRY" ]
+          then
+            echo "::error::amazon_ecr_registry is required when amazon_enable is true"
+            exit 64 # EX_USAGE
+          fi
+
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
@@ -467,6 +489,34 @@ jobs:
       id-token: write
 
     steps:
+      - name: Validate required inputs
+        env:
+          GOOGLE_PROJECT_ID: ${{ inputs.google_project_id }}
+          GOOGLE_REPOSITORY: ${{ inputs.google_repository }}
+          GOOGLE_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
+          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
+        run: |
+          if [ -z "$GOOGLE_PROJECT_ID" ]
+          then
+            echo "::error::google_project_id is required when google_enable is true"
+            exit 64 # EX_USAGE
+          fi
+          if [ -z "$GOOGLE_REPOSITORY" ]
+          then
+            echo "::error::google_repository is required when google_enable is true"
+            exit 64 # EX_USAGE
+          fi
+          if [ -z "$GOOGLE_WORKLOAD_IDENTITY_PROVIDER" ]
+          then
+            echo "::error::GOOGLE_WORKLOAD_IDENTITY_PROVIDER secret is required when google_enable is true"
+            exit 64 # EX_USAGE
+          fi
+          if [ -z "$GOOGLE_SERVICE_ACCOUNT" ]
+          then
+            echo "::error::GOOGLE_SERVICE_ACCOUNT secret is required when google_enable is true"
+            exit 64 # EX_USAGE
+          fi
+
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
