Don’t use deprecated :: commands

diff --git a/.github/workflows/jira.yaml b/.github/workflows/jira.yaml
--- a/.github/workflows/jira.yaml
+++ b/.github/workflows/jira.yaml
@@ -14,25 +14,25 @@ jobs:
 
           if [ -z "${{ vars.JIRA_DOMAIN }}" ]
           then
-            echo "::error::Missing var JIRA_DOMAIN. Set it to the origin you are accessing jira on, e.g. https://example.atlassian.net. It’s a good idea to set it on organisation level."
+            echo "ERROR: Missing var JIRA_DOMAIN. Set it to the origin you are accessing jira on, e.g. https://example.atlassian.net. It’s a good idea to set it on organisation level." 1>&2
             exit_code=78
           fi
 
           if [ -z "${{ vars.JIRA_USER }}" ]
           then
-            echo "::error::Missing var JIRA_USER. E-mail address of user to run this automation as. It’s a good idea to set it on organisation level."
+            echo "ERROR: Missing var JIRA_USER. E-mail address of user to run this automation as. It’s a good idea to set it on organisation level." 1>&2
             exit_code=78
           fi
 
           if [ -z "${{ secrets.JIRA_API_TOKEN }}" ]
           then
-            echo "::error::Missing secret JIRA_API_TOKEN. Generate one at https://id.atlassian.com/manage-profile/security/api-tokens . It’s a good idea to set it on organisation level."
+            echo "ERROR: Missing secret JIRA_API_TOKEN. Generate one at https://id.atlassian.com/manage-profile/security/api-tokens . It’s a good idea to set it on organisation level." 1>&2
             exit_code=78
           fi
 
           if [ -z "${{ vars.JIRA_STATUS_PR_DRAFT}}${{ vars.JIRA_STATUS_PR_READY }}${{ vars.JIRA_STATUS_PR_MERGED }}" ]
           then
-            echo "::error::Missing var JIRA_STATUS_PR_DRAFT, JIRA_STATUS_PR_READY or JIRA_STATUS_PR_MERGED. Set any of them to the status names you want to transition issues to when PRs are in draft, ready or merged state. It’s a good idea to set them on organisation level."
+            echo "ERROR: Missing var JIRA_STATUS_PR_DRAFT, JIRA_STATUS_PR_READY or JIRA_STATUS_PR_MERGED. Set any of them to the status names you want to transition issues to when PRs are in draft, ready or merged state. It’s a good idea to set them on organisation level." 1>&2
             exit_code=78
           fi
 
diff --git a/.github/workflows/notify-main-branch-failure.yaml b/.github/workflows/notify-main-branch-failure.yaml
--- a/.github/workflows/notify-main-branch-failure.yaml
+++ b/.github/workflows/notify-main-branch-failure.yaml
@@ -31,13 +31,13 @@ jobs:
           if [ -z "${{ secrets.SLACK_BOT_TOKEN }}" ]
           then
             # shellcheck disable=SC1111
-            echo "::error::Missing secret SLACK_BOT_TOKEN. Go to https://api.slack.com/apps/, create a bot, go to “OAuth & Permissions”. Add chate:write permission and grab a token."
+            echo "ERROR: Missing secret SLACK_BOT_TOKEN. Go to https://api.slack.com/apps/, create a bot, go to “OAuth & Permissions”. Add chate:write permission and grab a token." 1>&2
             exit_code=78
           fi
 
           if [ -z "${{ vars.SLACK_CHANNEL_ID }}" ]
           then
-            echo "::error::Missing var SLACK_CHANNEL_ID. This is _not_ a channel name. You can grab the ID from page URL."
+            echo "ERROR: Missing var SLACK_CHANNEL_ID. This is _not_ a channel name. You can grab the ID from page URL." 1>&2
             exit_code=78
           fi
 
